решение SFC
js-tasks-ru/vue-20230905_inkkolesov pull request #5
Opened 2023-09-18 17:51 UTC by inkoff

отправляю одним ПР.

2023-09-18 17:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-09-19 01:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-19 02:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-19 23:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-09-20 00:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-22 03:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-22 05:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-22 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-09-22 08:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-22 12:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-24 21:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-25 12:42 UTC, ShGKme commented on 03-sfc/01-VBindCover/babel.config.js
Этот файл лишний

2023-09-25 12:42 UTC, ShGKme commented on 03-sfc/01-VBindCover/babel.config.js
В целом в этой задаче добавлено много лишних файлов, dist, package.json. В задачнике уже есть сборщик, который запускает сервер для разработки и собирает исходники для всех задач. Дополнительно внутри задач их устанавливать не требуется.

2023-09-25 12:42 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionFade.vue
> +  transition: opacity 4s ease-in-out;
Этот компонент работал и без изменения стилей. Проблема в задаче только со вторым компонентом

2023-09-25 12:42 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div :class="[inline ? 'form-group_inline' : 'form-group']">
Во Vue, когда требуется добавить класс по условию, принято использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому выражению требуется добавлять.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects

2023-09-25 12:42 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div :class="[inline ? 'form-group_inline' : 'form-group']">
При этом класс `form-group` у компонента должен быть всегда, у него нет условия. Опциональный  класс только `form-group_inline`

2023-09-25 12:42 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +  transition: transform 4s;
С таким решением стили просто становятся глобальными. Это тоже самое, что не устанавливать `scoped` на `<style` совсем, а затронуты будут любые элементы с классом `.fade-list` в любом месте страницы.

Требуется сделать стили на столько инкапсулированными, на сколько возможно.

2023-09-25 12:42 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
Обычно параметры удобнее передавать отдельно, не оборачивая их в ещё один объект. Параметры (пропсы) фактически уже объект (`$props`).

Передача отдельных параметров удобнее пользователю компонента: видны отдельные параметры и их типы без дополнительной документации и TypeScript, не нужно обязательно оборачивать в объект при передаче.

```vue
<UiToast :toast="{ type: 'error', message: 'error' }" />
<UiToast type="error" message="error" />
```

2023-09-25 19:04 UTC, inkoff commented on 03-sfc/01-VBindCover/babel.config.js
Удалил все опыты по настройке сборщика

2023-09-25 19:05 UTC, inkoff commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionFade.vue
> +  transition: opacity 4s ease-in-out;
Поправил время.

2023-09-25 19:09 UTC, inkoff commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div :class="[inline ? 'form-group_inline' : 'form-group']">
привел к синтаксису по vue-практике

2023-09-25 19:10 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionFade.vue
> +  transition: opacity 4s ease-in-out;
Имеется в виду, что не должен был убираться атрибут `scoped` инкапсуляции стилей.

2023-09-25 19:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-25 19:33 UTC, inkoff commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
кое как понял суть, но понял. поправил.

2023-09-25 19:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-25 19:39 UTC, inkoff commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
тесты упали...

2023-09-25 19:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-25 19:49 UTC, inkoff commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
пофиксил. но не факт что правильно. в первом варианте как-то меньше кода и понятнее, что мы закидываем целый объект, а дочерний - сам разбирается что из свойств ему надо...

2023-09-27 05:32 UTC, inkoff commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionFade.vue
> +  transition: opacity 4s ease-in-out;
Готово

2023-09-27 05:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-27 05:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-27 05:52 UTC, inkoff commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +  transition: transform 4s;
поправил на ::v-deep().

2023-09-27 18:21 UTC, ShGKme requested changes

2023-09-27 18:21 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
Эти стили не работают. Анимация отсутствует, а такое применение `v-deep` не совсем корректное.

`v-deep` - это псевдо-селектор для выбора элементов внутри другого элемента с отключением инкапсуляции.

`a :deep(b)` - выбирает все `b` внутри инкапсулированного `a`.

Если `:deep` используется для всего селектора, он всё равно работает, как селектор для элементов внутри инкапсулированного компонента.

`::v-deep(.fade-list)` превращается в `[data-v-eae4993b] .fade-list`.

2023-09-30 10:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-30 10:13 UTC, inkoff commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
>  }
разобрался со scoped module и инкапсуляцией стилей. поправил код - теперь больше похоже на пример работы как в Readme.MD

2023-09-30 10:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-30 11:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-30 11:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-30 14:48 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionFade.vue
> +<style>
Отключение инкапсуляции этого компонента — лишнее. Так его стили становятся глобальными, хотя они корректно работали и с инкапсуляцией.

2023-09-30 16:26 UTC, inkoff commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionFade.vue
> +<style>
вернул.

2023-09-30 16:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-30 19:03 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-09-30 19:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-01 09:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-01 10:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-01 13:09 UTC, ShGKme approved these changes
Все задачи приняты

2023-10-01 13:10 UTC, merged