Решение vue-router
js-tasks-ru/vue-20230905_inkkolesov pull request #7
Opened 2023-10-13 11:17 UTC by inkoff

2023-10-13 11:18 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-13 11:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-13 13:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-15 10:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-15 15:51 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +          >
Устанавливать здесь обработчик события клика на кнопку не нужно.

Клик на кнопку — всего лишь один из путей сабмита формы. Но она также может сабмититься, например, нажатием на `Enter` или прямым вызовом метода формы.

`submit` - это событие именно всей формы (`<form>`). В этой задаче обработчик события сабмита формы уже добавлен.

2023-10-15 15:51 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageRegister.vue
> +          </button>
Аналогично здесь

2023-10-15 15:51 UTC, ShGKme commented on 05-vue-router/05-AuthGuard/router/index.js
> +});
Вариант с использованием коллбека `next` работает в Vue Router 4, но это устаревший вариант из Vue 2.

В актуальном роутере можно просто возвращать значение как напрямую `return`-ом так и через промис.

2023-10-15 15:51 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      :class="[{ 'form-control_rounded': rounded }, { 'form-control_sm': small }]"
Вместо массива с двумя объектами можно описать один объект с двумя классами по двум условиям.

2023-10-15 15:51 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      v-bind="$attrs"
Здесь все атрибуты устанавливаются на оборачиваемый элемент. Но они всё ещё наследуются по умолчанию корневым элементом. Это поведение нужно отключить.

2023-10-16 17:53 UTC, inkoff commented on 05-vue-router/05-AuthGuard/router/index.js
> +});
использовал beforeResolve

2023-10-16 17:54 UTC, inkoff commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      v-bind="$attrs"
добавил `inheritAttrs: false,`

2023-10-16 17:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-16 21:24 UTC, ShGKme reviewed
Все решённые задачи приняты, но есть новые добавленные задачи.

2023-10-16 21:24 UTC, ShGKme commented on 05-vue-router/05-AuthGuard/router/index.js
> +});
`beforeEach` здесь также можно использовать

2023-10-17 16:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-17 16:21 UTC, inkoff commented on 05-vue-router/05-AuthGuard/router/index.js
> +});
Поправил наименование метода.

2023-10-18 12:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-18 14:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-19 11:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-20 06:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-20 15:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-20 18:53 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +    },
Загружаются ли новые выбранные файлы через `uploader` или нет - не влияет на то, что клик при наличии картинки (в том числе превью) должен удалять картинку.

Здесь не должно быть зависимости от `uploader`

2023-10-20 18:53 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +  },
Свойство `deletePreview` кажется лишним. Текст "удалить изображение" выводится, если оно есть (выбрано или изначально в preview). Для этого не нужен дополнительный флаг.

2023-10-20 18:54 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +    },
Здесь нет отмены действия клика. Клик при удалении вызывает открытие окна выбора файла

2023-10-20 18:59 UTC, inkoff commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +    },
![image](https://github.com/js-tasks-ru/vue-20230905_inkkolesov/assets/18501137/cc66b02b-73ba-4a4c-bd38-033ca49e717f)
не нашел другого места где это поправить.

2023-10-20 19:00 UTC, inkoff commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +  },
Не используя этот флаг - не понимаю как переопределить поведение text, точнее обнулить значение preview

2023-10-20 19:00 UTC, inkoff commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +    },
Разбрусь.

2023-10-20 21:02 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +    },
Здесь проверяется, что клик не работает именно в процессе загрузки, а не когда загрузчик в целом есть.

Проще всего иметь флаг того, что сейчас идёт загрузка (true перед началом загрузки, false после окончания), и отключать поле ввода с disabled

2023-10-20 21:03 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +  },
Теперь понял. Да, при таком подходе к решению нужен ещё один флаг.

2023-10-21 13:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-21 13:41 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-21 13:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-22 08:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-23 07:00 UTC, ShGKme requested changes

2023-10-23 07:00 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +  <UiInput :type="type" :step="step" v-model="modelValueProxy" @input="onInput">
Здесь ввод нового значения обрабатывается дважды и приводит к порождению двух событий разного значения: один раз в `modelValueProxy` сеттере за счёт двустороннего связывания `v-model`, и один раз по событию `input`.

2023-10-23 07:00 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      },
Красивое решение

2023-10-23 07:00 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +  <UiInput :type="type" :step="step" v-model="modelValueProxy" @input="onInput">
Если ввод обрабатывается по событию `input`, то `v-model` уже не нужен. Должно только передаваться значение без обработки события его обновления `@update:modelValue`

2023-10-23 10:13 UTC, inkoff commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +  <UiInput :type="type" :step="step" v-model="modelValueProxy" @input="onInput">
![image](https://github.com/js-tasks-ru/vue-20230905_inkkolesov/assets/18501137/5e66b220-1035-4968-9cac-fce4dd9f6fad)
убираю сеттер из проксирвоанной v-model, в консоли появляются предупреждения. их игнорировать?

2023-10-23 10:13 UTC, inkoff commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      },
я Вам в лс писал про это решение.

2023-10-23 10:15 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-23 17:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-24 22:26 UTC, ShGKme requested changes

2023-10-24 22:26 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +  <UiInput :type="type" :step="step" v-model="modelValueProxy" @input="onInput">
В текущем решении осталась старая проблема. Всё ещё используется двустороннее связывание с директивой `v-model`. Если ввод обрабатывается через `@input`, то его уже не нужно обрабатывать второй раз по событию обновления модели.

Вместо двустороннего связывания тут должно только передаваться значение модели.

2023-10-25 18:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-25 18:13 UTC, inkoff commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +  <UiInput :type="type" :step="step" v-model="modelValueProxy" @input="onInput">
+

2023-11-05 09:23 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-05 21:54 UTC, ShGKme approved these changes
Все задачи приняты

2023-11-05 21:58 UTC, merged